"""Add Category and relation

Revision ID: 968eeda7ca8c
Revises: 905d2b91bac9
Create Date: 2025-11-30 18:07:27.651780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968eeda7ca8c'
down_revision = '905d2b91bac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_products_category_id_categories',  # будь-яке унікальне ім’я
            'categories',
            ['category_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('categories')
    # ### end Alembic commands ###
