"""Add active to Product

Revision ID: f719a7b8583f
Revises: f158eb0f96e4
Create Date: 2025-11-30 18:17:53.694154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f719a7b8583f"
down_revision = "f158eb0f96e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "active",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=120),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "price",
            existing_type=sa.FLOAT(),
            type_=sa.Numeric(precision=10, scale=2),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Numeric(precision=10, scale=2),
            type_=sa.FLOAT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=120),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )
        batch_op.drop_column("active")
    # ### end Alembic commands ###
